(executables
 (names
  server1
  server2
  client1
  docker_client
  client_timeout
  client_tls
  client_proxy)
 (libraries
  cohttp-eio
  eio_main
  eio.unix
  fmt
  unix
  logs.fmt
  logs.threaded
  tls-eio
  ca-certs
  mirage-crypto-rng.unix
  cmdliner))

; (executable
;  (name client_proxy)
;  (libraries cohttp-eio eio_main eio.unix fmt base64))

(alias
 (name runtest)
 (package cohttp-eio)
 (deps server1.exe))
